<?php
// site configuration
$config = array();

// debug mode?
$config['deployment_hostnames'] = array('example.com', 'www.example.com');
$config['debug'] = !(in_array(strtolower($_SERVER['SERVER_NAME']), $config['deployment_hostnames']));

// language
$config['lang'] = 'en';
$config['timezone'] = 'Europe/Berlin';

// ...
$config['app_name'] = 'mysite';
$config['app_title'] = 'My site';

// server-related
$config['document_root'] = dirname(__FILE__).'/../public/';
$config['base_url'] = 'http://'.$_SERVER['SERVER_NAME'].'/';
$config['media_url'] = $config['base_url'].'static/';

// session support
$config['sessions_enabled'] = false;
$config['session_save_path'] = session_save_path();

// fancy URLs
// If this setting is set to true, all URLs generated by the {url} Smarty template function will return "pretty" URLs, like "example.com/legal/" instead of "example.com/index.php?action=legal".
// Before enabling this, you need to uncomment the first few lines of the included ".htaccess" file or, if you're not using Apache, configure your web server to rewrite URLs accordingly.
$config['fancy_urls'] = false;

// log file
$config['logfile'] = $config['document_root'].'../../log/'.$config['app_name'].($config['debug'] ? '_debug' : '').'.log';

// Smarty template engine
$config['smarty'] = array();
$config['smarty']['template_dir'] = dirname(__FILE__).'/templates/';
$config['smarty']['template_compile_dir'] = $config['smarty']['template_dir'].'compiled';
$config['smarty']['template_cache_dir'] = $config['smarty']['template_dir'].'cached';
$config['smarty']['template_caching_enabled'] = !$config['debug'];

// analytics
$config['analytics'] = array();
$config['analytics']['enabled'] = false;
$config['analytics']['google_analytics_id'] = 'UA-XXXXX-X';

// cache busting
$config['cache_buster'] = '?3';
?>
